version: "3.9"
services:
  problem_sheet_api:
    build: ./API
    ports:
      - "5001:5001"
  frontend:
    build: ./frontend/problem-generation
    ports:
      - "3000:3000"
  transaction_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql