# Use the official Node.js image as the base image
FROM node:14

# Set the working directory inside the container
WORKDIR /frontend

# Copy the package.json and package-lock.json files into the container
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application files into the container
COPY . .

# Expose the port that the application will run on
EXPOSE 3000

# Start the Node.js application
CMD ["npm", "start"]
