# Use the official Python image as the base image
FROM python:3.11

# Set the working directory inside the container
WORKDIR /api

# Copy the requirements.txt file into the container
COPY requirements.txt .

# Install the dependencies
RUN pip install -r requirements.txt

# Copy the rest of the application files into the container
COPY . .

# Expose the port that the application will run on
EXPOSE 5001

# Start the Python application
CMD ["python", "api.py"]
